server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.247.133:8858
      http-method-specify: true



